# ==================== 开发环境配置 ====================
spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 5
      timeout: 5000ms
      lettuce:
        shutdown-timeout: 2000ms
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms
          time-between-eviction-runs: 60000ms

# 开发环境日志级别
logging:
  level:
    root: INFO
    '[com.moyuan]': DEBUG
    '[org.springframework]': WARN
