-- H2数据库测试schema

-- 朝代表
CREATE TABLE IF NOT EXISTS dynasty (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  start_year INT DEFAULT NULL,
  end_year INT DEFAULT NULL,
  description TEXT DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (name)
);

-- 诗人表
CREATE TABLE IF NOT EXISTS poet (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  courtesy_name VARCHAR(50) DEFAULT NULL,
  pseudonym VARCHAR(50) DEFAULT NULL,
  dynasty_id BIGINT DEFAULT NULL,
  birth_year INT DEFAULT NULL,
  death_year INT DEFAULT NULL,
  birthplace VARCHAR(100) DEFAULT NULL,
  biography TEXT DEFAULT NULL,
  life_story TEXT DEFAULT NULL,
  influence TEXT DEFAULT NULL,
  evaluation TEXT DEFAULT NULL,
  anecdotes TEXT DEFAULT NULL,
  avatar VARCHAR(255) DEFAULT NULL,
  poet_type VARCHAR(20) DEFAULT 'ancient',
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

-- 分类表
CREATE TABLE IF NOT EXISTS category (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (name)
);

-- 诗词表
CREATE TABLE IF NOT EXISTS poem (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  dynasty_id BIGINT NOT NULL,
  poet_id BIGINT DEFAULT NULL,
  category_id BIGINT DEFAULT NULL,
  translation TEXT DEFAULT NULL,
  appreciation TEXT DEFAULT NULL,
  background TEXT DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  view_count INT NOT NULL DEFAULT 0,
  like_count INT NOT NULL DEFAULT 0,
  favorite_count INT NOT NULL DEFAULT 0,
  is_original TINYINT NOT NULL DEFAULT 0,
  poem_type VARCHAR(20) DEFAULT 'classical',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (dynasty_id) REFERENCES dynasty(id),
  FOREIGN KEY (poet_id) REFERENCES poet(id),
  FOREIGN KEY (category_id) REFERENCES category(id)
);

-- 用户表
CREATE TABLE IF NOT EXISTS user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  avatar VARCHAR(255) DEFAULT NULL,
  bio VARCHAR(500) DEFAULT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE (username)
);

-- 论坛帖子表
CREATE TABLE IF NOT EXISTS forum_post (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  category VARCHAR(50) DEFAULT NULL,
  view_count INT NOT NULL DEFAULT 0,
  like_count INT NOT NULL DEFAULT 0,
  comment_count INT NOT NULL DEFAULT 0,
  is_top TINYINT NOT NULL DEFAULT 0,
  is_featured TINYINT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  audit_reason VARCHAR(500) DEFAULT NULL,
  audit_time TIMESTAMP DEFAULT NULL,
  last_comment_time TIMESTAMP DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user(id)
);

-- 评论表
CREATE TABLE IF NOT EXISTS comment (
  id BIGINT NOT NULL AUTO_INCREMENT,
  content TEXT NOT NULL,
  user_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  target_type TINYINT NOT NULL,
  parent_id BIGINT DEFAULT NULL,
  reply_to_user_id BIGINT DEFAULT NULL,
  like_count INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  audit_reason VARCHAR(500) DEFAULT NULL,
  audit_time TIMESTAMP DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  FOREIGN KEY (user_id) REFERENCES user(id)
);

-- 用户点赞表
CREATE TABLE IF NOT EXISTS user_like (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (user_id, target_id, target_type)
);

-- 用户收藏表
CREATE TABLE IF NOT EXISTS user_favorite (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (user_id, target_id, target_type)
);

-- 浏览历史表
CREATE TABLE IF NOT EXISTS user_history (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  target_type VARCHAR(20) NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_user_history_user_id (user_id),
  INDEX idx_user_history_target (target_id, target_type)
);

-- 首页导航表
CREATE TABLE IF NOT EXISTS home_navigation (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  icon VARCHAR(255) DEFAULT NULL,
  link VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- AI模型配置表
CREATE TABLE IF NOT EXISTS ai_model (
  id BIGINT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  provider VARCHAR(50) NOT NULL,
  model_id VARCHAR(100) NOT NULL,
  api_key VARCHAR(255) DEFAULT NULL,
  api_url VARCHAR(255) DEFAULT NULL,
  description VARCHAR(500) DEFAULT NULL,
  status TINYINT NOT NULL DEFAULT 1,
  is_default TINYINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- 精选诗人表
CREATE TABLE IF NOT EXISTS poet_featured (
  id BIGINT NOT NULL AUTO_INCREMENT,
  poet_id BIGINT NOT NULL,
  reason VARCHAR(500) DEFAULT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  FOREIGN KEY (poet_id) REFERENCES poet(id),
  UNIQUE (poet_id)
);

-- 操作日志表
CREATE TABLE IF NOT EXISTS operation_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT DEFAULT NULL,
  username VARCHAR(50) DEFAULT NULL,
  operation VARCHAR(50) NOT NULL,
  method VARCHAR(200) NOT NULL,
  params TEXT DEFAULT NULL,
  ip VARCHAR(50) DEFAULT NULL,
  duration BIGINT DEFAULT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- 视界文章表
CREATE TABLE IF NOT EXISTS vision_article (
  id BIGINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  summary VARCHAR(500) DEFAULT NULL,
  cover_image VARCHAR(255) DEFAULT NULL,
  author_id BIGINT DEFAULT NULL,
  view_count INT NOT NULL DEFAULT 0,
  like_count INT NOT NULL DEFAULT 0,
  comment_count INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

-- 诗词内容缓存表
CREATE TABLE IF NOT EXISTS poem_content_cache (
  id BIGINT NOT NULL AUTO_INCREMENT,
  poem_title VARCHAR(100) NOT NULL,
  poet_name VARCHAR(50) NOT NULL DEFAULT '',
  content_type VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'ai',
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE (poem_title, poet_name, content_type)
);