/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AncientPoemSelection: typeof import('./components/home/AncientPoemSelection.vue')['default']
    AppFooter: typeof import('./components/common/AppFooter.vue')['default']
    AppHeader: typeof import('./components/common/AppHeader.vue')['default']
    AuthHeader: typeof import('./components/common/AuthHeader.vue')['default']
    BackToTop: typeof import('./components/common/BackToTop.vue')['default']
    ContemporaryPoems: typeof import('./components/home/ContemporaryPoems.vue')['default']
    DailyPoetry: typeof import('./components/business/DailyPoetry.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTag: typeof import('element-plus/es')['ElTag']
    ErrorMessage: typeof import('./components/common/ErrorMessage.vue')['default']
    ForumPost: typeof import('./components/business/ForumPost.vue')['default']
    ForumPreview: typeof import('./components/home/ForumPreview.vue')['default']
    HomeCarousel: typeof import('./components/home/HomeCarousel.vue')['default']
    HomeNavBar: typeof import('./components/business/HomeNavBar.vue')['default']
    HomeNavigation: typeof import('./components/business/HomeNavigation.vue')['default']
    ImageUpload: typeof import('./components/common/ImageUpload.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    LoginDropdown: typeof import('./components/business/LoginDropdown.vue')['default']
    LoginPrompt: typeof import('./components/common/LoginPrompt.vue')['default']
    PoemCard: typeof import('./components/business/PoemCard.vue')['default']
    PoetCard: typeof import('./components/business/PoetCard.vue')['default']
    PoetryDetailDialog: typeof import('./components/business/PoetryDetailDialog.vue')['default']
    PoetrySearch: typeof import('./components/business/PoetrySearch.vue')['default']
    QrCodeLink: typeof import('./components/common/QrCodeLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
